services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: scraper_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  scrapy:
    build: .
    container_name: scrapy_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/scraper_db
    volumes:
      - .:/app
      - ./images:/images # Ensure the images folder is shared between host and container
    command: ["sh", "-c", "scrapy crawl trip"]

volumes:
  db_data:
